apiVersion: v1
kind: Service
metadata:
  name: ai-guardian-remediation
  labels:
    component: ai-guardian-remediation
spec:
  ports:
  - name: ai-guardian-remediation
    port: 8588
    protocol: TCP
    targetPort: 8588
  selector:
    component: ai-guardian-remediation